<div class="row">
    <div class="col-sm-6">
        <h3>STATS</h3>
        <div class="row">
            <div class="col-sm-6">
                <div class="cpu stat">
                    Load Average: <span data-attribute="loadAverage" data-model="system"></span>
                </div>
                <div class="processes stat">
                    Processes: <span data-attribute="processes" data-model="system"></span>
                </div>
                <div class="uptime stat">
                    Uptime: <span data-attribute="uptime" data-model="system"></span> 
                </div>
            </div>
            <div class="col-sm-6">

            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <h3>LOGS</h3>
        <div class="logs stat"></div>
    </div>
</div>