<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Robot</title>
    <?php $this->assets->outputCss() ?>
</head>
<body>

<div class="container">
    <div class="header-nav navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="row">
        <div class="col-sm-3">
            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav nav-stacked">
                    <li><a href="/">Dashboard</a></li>
                    <li><a href="/">Logs</a></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-9">
            <?php echo $this->getContent(); ?>
        </div>
    </div>

</div>

<?php $this->assets->outputJs() ?>
</body>
</html>

