<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="/img/robot_icon.png">
        <link rel="apple-touch-startup-image" href="/img/robot_icon.png">

        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <title>Robot</title>
        <?php $this->assets->outputCss() ?>
    </head>
    <body>
        <nav class="header-nav">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-flash" aria-hidden="true"></span></a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
        </nav>

        <div id="content" class="container">
            <div class="row">
                <div id="main-nav" class="col-sm-3 collapse navbar-collapse">
                    <ul class="nav nav-stacked">
                        <li class="active"><a href="/"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>Dashboard</a></li>
                        <li><a href="/"><span class="glyphicon glyphicon-time" aria-hidden="true"></span>Logs</a></li>
                    </ul>
                </div>
                <div id="content" class="col-sm-9">
                    <?php echo $this->getContent(); ?>
                </div>
            </div>

        </div>

        <?php $this->assets->outputJs() ?>
    </body>
</html>

