<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="/img/robot-icon.png">
        <link rel="apple-touch-startup-image" href="/img/robot-icon.png">

        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <title>Robot</title>
        <?php $this->assets->outputCss() ?>
    </head>
    <body>
        <div class="main">
            <?php echo $this->getContent(); ?>
        </div>
        <?php $this->assets->outputJs() ?>
    </body>
</html>

